services: 
  ollama:
    image: ollama/ollama
    ports: 
      - "11434:11434"
    volumes: 
      - ollama_data:/root/.ollama
    networks:
      - app_network

  bot: 
    build: .
    command: bash -c "export PYTHONPATH=/app && python telegram_bot/bot.py"
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - app_network
    env_file:
      - .env

  fastapi:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - app_network
    env_file:
      - .env
  
  

volumes:
  ollama_data:

networks:
  app_network:
   driver: bridge
  